### ISSUE TITLE
Please add a license file

### ISSUE THREAD

**Issue by unixorn** [ThemysciraData/conda.plugin.zsh#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but it doesn't have a license file.

Please add a license file - if you don't have one in mind,  I recommend using [choosealicense.com](https://choosealicense.com) to help choose an appropriate one.

Thanks!

**Comment by KellieOwczarczak** [comment]
That site was not very helpful for me. 😬 It just gave me too many options that all seem right and wrong at the same time. I'll get to it I guess.

**Comment by unixorn** [comment]
Apache 2.0 and MIT are both good options.

**Comment by KellieOwczarczak** [comment]
Gemacht. Went MIT. Seems like that's what others use after looking at some.
